### ISSUE TITLE
Weapon balance

### ISSUE THREAD

**Issue by Austioli** [N1GHTPATROL/TNP-3.X#25]
Ash 12 is super op, it has been for a while but now the players are starting to abuse it... it one shots without a helmet, does like 98 with a helmet, has good range, is cheap, has little recoil and has an insane fire rate. I think the ash 12 should be made either an airdrop only weapon, have it's damage nerfed, or have it's price jacked up. <3

**Comment by N1GHTPATROL** [comment]
Hi, I'll be hopefully continuing the weapon balance in the near future. I've been sick so that is why this has had a delay. Thanks for the feedback.
