### ISSUE TITLE
New Vehicles

### ISSUE THREAD

**Issue by themisfitgames** [N1GHTPATROL/TNP-3.X#7]
New vehicles instead of M3 Lee, replace that vehicle pack with this [workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1375451337) though we can remove some vehicles from the workshop before reuploading. 

Per example:

Fennek with missile - 6204
Fennek (desert) - 6202
Fennek (forest) - 6203

or something like that.

**Comment by N1GHTPATROL** [comment]
Yeah the M3 lee is like 13mb, we could fit 2-3 vehicles in for that much
